### ISSUE TITLE
v0.3 in pypi

### ISSUE THREAD

**Issue by wgordon17** [PaesslerAG/django-currentuser#22]
When will v0.3 be published to pypi?

**Comment by Eorhim** [comment]
@wgordon17 We had a problem with the pipeline and Python 3.7 so we removed the support for Python 3.7 for now. I hope the new version will be available soon.

**Comment by Eorhim** [comment]
OK, pipeline is still broken. 😦 

Working on it.

**Comment by belugame** [comment]
@wgordon17 it is on pypi now:
https://pypi.org/project/django-currentuser/0.3.2/
