### ISSUE TITLE
Support for Django 2.2

### ISSUE THREAD

**Issue by fabio-filho** [PaesslerAG/django-currentuser#27]
Talking about the support for Django 2.2, is there anything related on the roadmapping?

**Comment by lino** [comment]
Is there even anything that needs to be done besides changing dependencies?

**Comment by djkgamc** [comment]
Seems to work if you just ignore the < 2.2 requirement. Might have been a mistake

**Comment by zsoldosp** [comment]
linking PR #28 to this issue

**Comment by Eorhim** [comment]
This is addressed in pull request #29. It was slightly more involved than just updating the referenced versions, but no big deal.

**Comment by zsoldosp** [comment]
As per https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

2.2 Django only supports python versions 3.5 and upwards. Which python version are you using? #29 seems to have set it up correctly to me

(copying comment from duplicate issue #30 and PR #31 is also related)

**Comment by zsoldosp** [comment]
I think the root cause of the problem is that the first line of the install_requires is not bound by python version, thus always gets applied (from #31 comment)

**Comment by serafss2** [comment]
Pull request #33 should fix this issue

**Comment by serafss2** [comment]
I just tested, it's fixed in `0.4.2`, this can be closed
