### ISSUE TITLE
don't enforce supported versions in setup.py?

### ISSUE THREAD

**Issue by zsoldosp** [PaesslerAG/django-currentuser#32]
inspired by #27, #30, #31 

It could be better NOT to specify the python and Django versions, just as a super low bar - i.e.: python 2.7 and Django 1.11, and simply list in the README (tox) which versions are supported

* Each Django ensures it can only be installed with the right python version AFAIK,  so the django version-python version match is taken care of
* we could end up with users installing the app on unsupported Django versions (e.g.: 2.0), but then if they come to report a bug, we can just remind them it is not supported
* we don't have to test against unsupported versions in tox/travis

Would simplify life quite a bit as setuptools is never trivial :)

**Comment by serafss2** [comment]
I agree with this, I can test with no python version and make a PR if you want @zsoldosp

**Comment by serafss2** [comment]
@zsoldosp Should we still let travis test all supported environments? aka 1.11, 2.1, 2.2? I think we should still test on the supported django versions

**Comment by zsoldosp** [comment]
@serafss2 yes,of course we should keep testing all supported python-django combinations in tox/travis! I'll take a look at the PR, but will wait for feedback from someone at @PaesslerAG
