### ISSUE TITLE
Release version 0.4.2 on Pypi

### ISSUE THREAD

**Issue by serafss2** [PaesslerAG/django-currentuser#34]
Just an update on when will the next release roll-out on Pypi? I still have to import directly from git, the latest commit fixes my problem now.

Thank you!

**Comment by belugame** [comment]
@serafss2 Hey, sorry for the delay. Will help you to get this released. Any reason you skipped 0.4.1?

**Comment by serafss2** [comment]
Hi @belugame, ty for your help! No reason, it's just when I go here: https://pypi.org/project/django-currentuser/ I see that the current version in the header is `0.4.1` but in the release notes underneath it says `0.4.0`, wasn't sure which it was!

Let me know if you want me to put `0.4.1` instead, I'll forcepush that

**Comment by serafss2** [comment]
Update: https://pypi.org/project/django-currentuser/#history looks like there was 2 releases on May 7th (`0.4.0` and `0.4.1`)
