### ISSUE TITLE
Django v. 3.0 compatibility

### ISSUE THREAD

**Issue by snake-soft** [PaesslerAG/django-currentuser#38]
I tested it with version 0.4.2 and it seems to work fine with django3.0 after editing parameters in setup.py.

**Comment by mattLLVW** [comment]
@belugame any news about this?

**Comment by belugame** [comment]
@mattLLVW  @jimothyGator sorry for the long delay
can you increase the version number for a new release, please? may be not the only spot where it is specified:

https://github.com/PaesslerAG/django-currentuser/blob/master/django_currentuser/__init__.py

**Comment by mattLLVW** [comment]
@belugame done.

**Comment by jimcushing-natgeo** [comment]
@belugame Also done. Note that the main differences between the two PRs (mine and @mattLLVW's) is that mine would allow 3.0 but not 3.1 or 4.0, and that Tox will run tests under Django 3.0. 3.1 is an unknown at this stage, so I was conservative and didn't include it.

**Comment by mattLLVW** [comment]
@jimcushing-natgeo 
1/ Why did you do a PR when mine was already submitted?
2/ Threre's a high security issue with Django 3.0 you should look into it.
3/ After seeing how long it takes for maintainers to merge one line of code and produce a new version, and how useless Django limitation is, i don't think been conservative is in order.

**Comment by jimothyGator** [comment]
Good questions. The main reason was to include the update to `tox.ini`. 

Note that my change will work on Django 3.0.2 as well. It just won't work with Django 3.1 (which doesn't exist yet). Will django-currentuser work with with Django 3.1 without additional changes? Your guess is as good as mine, which is why I went with the conservative approach.

**Comment by belugame** [comment]
@jimothyGator  Thank you for setting things straight. 
 @mattLLVW: 
- We aim to support the latest stable release and want test coverage of all version combinations, which your MR did not give. 
- Leaving it open to future releases or untested combinations could break people's projects while the merged changes does not stop anyone from using a 3.0 bugfix version.

**Comment by belugame** [comment]
Feel free to tag one of the main contributors if you think you ticked all boxes in terms of QA, and hopefully next time we have more time at hands to react in a fast manner. Appreciate your contributions :)

**Comment by belugame** [comment]
@jimothyGator  @snake-soft  @mattLLVW  0.4.3 is now on pypi

https://pypi.org/project/django-currentuser/0.4.3/
