### ISSUE TITLE
Key (modified_by_id)=(1) is not present in table "account_customuser" when running unit test

### ISSUE THREAD

**Issue by paulexconde** [PaesslerAG/django-currentuser#47]

**Comment by bethlakshmi** [comment]
I'm having the same problem

**Comment by zvyn** [comment]
A workaround is to set the user to `None` explicitly when setting up the test. For `pytest` this works for me:
```python
@pytest.fixture(autouse=True)
def unset_user():
    from django_currentuser.middleware import _set_current_user

    _set_current_user()
```

**Comment by paulexconde** [comment]
> A workaround is to set the user to `None` explicitly when setting up the test. For `pytest` this works for me:
> 
> ```python
> @pytest.fixture(autouse=True)
> def unset_user():
>     from django_currentuser.middleware import _set_current_user
> 
>     _set_current_user()
> ```

@zvyn , Thanks 👍
