### ISSUE TITLE
Django >1.11 support

### ISSUE THREAD

**Issue by vesatoivonen** [PaesslerAG/django-currentuser#9]
Will Django 1.11.1 and 2.0.1 be supported by the pip package any time soon?

**Comment by zsoldosp** [comment]
1.11 seems to be already supported https://github.com/PaesslerAG/django-currentuser/blob/master/tox.ini

**Comment by vesatoivonen** [comment]
1.11 yes, but not 1.11.1, which pip downgraded for me during installation.

**Comment by zsoldosp** [comment]
ah, I see the bug there - it's in [setup.py](https://github.com/PaesslerAG/django-currentuser/blob/master/setup.py#L34) - it should read `<1.12` instead of `<=1.11` :(

**Comment by kairichard** [comment]
@vesatoivonen @zsoldosp A new version is available at https://pypi.python.org/pypi/django-currentuser containing the bug fix. Thank you for reporting.

**Comment by vesatoivonen** [comment]
Works nicely for 1.11.1, thanks.

**Comment by kairichard** [comment]
@vesatoivonen You can follow/watch #11 to be notified once there is support for django >= 2.0 available.
